function buildEmail({ name, city }) {
  return {
    title: "Defund NYPD",
    subject: "DEFUND NYPD",
    body: `Dear New York City Council Members,\n\nMy name is ${
      name || "[YOUR NAME]"
    } and I am a resident of ${
      city || "[BOROUGH]"
    }. Last April, NYC Mayor Bill De Blasio proposed major budget cuts for the Fiscal Year 2021, especially to education and youth programs, while refusing to slash the NYPD budget by any significant margin.\n\nI am emailing today to demand that you vote no on the Mayor’s FY21 proposed budget. Furthermore, I urge you ONLY to vote for a budget that includes AT LEAST $1 billion in cuts to the NYPD with equal reallocation towards social services and education programs, effective at the beginning of FY21, July 1, 2020.\n\nGovernor Cuomo has doubled the presence of the NYPD on New York City streets. I am asking that city officials lobby the same amount of attention and effort towards finding sustainable, longterm change.\n\nThank you.`,
    args: {
      name: {
        label: "Your name",
        inputType: "text",
      },
      city: { label: "Borough", inputType: "text" },
    },
    directRecipient: `bdeblasio@cityhall.nyc.gov`,
    receivers: [
      {
        label: "District 1",
        name: "Margaret S. Chin",
        email: "chin@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 2",
        name: "Carlina Rivera",
        email: "District2@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 3",
        name: "Corey Johnson",
        email: "SpeakerJohnson@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 4",
        name: "Keith Powers",
        email: "KPowers@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 5",
        name: "Ben Kallos",
        email: "BKallos@BenKallos.com",
        autoSelect: true,
      },
      {
        label: "District 6",
        name: "Helen Rosenthal",
        email: "Helen@HelenRosenthal.com",
        autoSelect: true,
      },
      {
        label: "District 7",
        name: "Mark Levine",
        email: "District7@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 8",
        name: "Diana Ayala",
        email: "DAyala@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 9",
        name: "Bill Perkins",
        email: "D09perkins@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 10",
        name: "Ydanis Rodriguez",
        email: "yrodriguez@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 11",
        name: "Andrew Cohen",
        email: "District11@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 12",
        name: "Andy King",
        email: "Andy.King@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 13",
        name: "Mark Gjonaj",
        email: "MGjonaj@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 14",
        name: "Fernando Cabrera",
        email: "fcabrera@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 15",
        name: "Ritchie J. Torres",
        email: "Rtorres@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 16",
        name: "Vanessa L. Gibson",
        email: "District16Bronx@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 17",
        name: "Rafael Salamanca Jr.",
        email: "salamanca@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 18",
        name: "Ruben Diaz, Sr.",
        email: "RDiaz@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 19",
        name: "Paul Vallone",
        email: "district19@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 20",
        name: "Peter Koo",
        email: "pkoo@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 21",
        name: "Francisco Moya",
        email: "FMoya@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 22",
        name: "Costa Constantinides",
        email: "",
        autoSelect: true,
      },
      {
        label: "District 23",
        name: "Barry Grodenchik",
        email: "BGrodenchik@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 24",
        name: "Rory I. Lancman",
        email: "RLancman@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 25",
        name: "Daniel Dromm",
        email: "dromm@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 26",
        name: "Jimmy Van Bramer",
        email: "JVanBramer@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 27",
        name: "I. Daneek Miller",
        email: "",
        autoSelect: true,
      },
      {
        label: "District 28",
        name: "Adrienne E. Adams",
        email: "Adams@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 29",
        name: "Karen Koslowitz",
        email: "Koslowitz@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 30",
        name: "Robert Holden",
        email: "District30@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 31",
        name: "Donovan J. Richards",
        email: "drichards@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 32",
        name: "Eric A. Ulrich",
        email: "eulrich@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 33",
        name: "Stephen T. Levin",
        email: "slevin@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 34",
        name: "Antonio Reynoso",
        email: "areynoso@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 35",
        name: "Laurie A. Cumbo",
        email: "LCumbo@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 36",
        name: "Robert E. Cornegy, Jr.",
        email: "district36@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 37",
        name: "Vacant",
        email: "District37@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 38",
        name: "Carlos Menchaca",
        email: "info38@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 39",
        name: "Brad Lander",
        email: "lander@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 40",
        name: "Mathieu Eugene",
        email: "meugene@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 41",
        name: "Alicka Ampry-Samuel",
        email: "District41@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 42",
        name: "Inez Barron",
        email: "",
        autoSelect: true,
      },
      {
        label: "District 43",
        name: "Justin Brannan",
        email: "AskJB@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 44",
        name: "Kalman Yeger",
        email: "AskKalman@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 45",
        name: "Farah N. Louis",
        email: "District45@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 46",
        name: "Alan N. Maisel",
        email: "AMaisel@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 47",
        name: "Mark Treyger",
        email: "MTreyger@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 48",
        name: "Chaim M. Deutsch",
        email: "cdeutsch@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 49",
        name: "Deborah Rose",
        email: "DROSE@Council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 50",
        name: "Steven Matteo",
        email: "SMatteo@council.nyc.gov",
        autoSelect: true,
      },
      {
        label: "District 51",
        name: "Joseph C. Borelli",
        email: "borelli@council.nyc.gov",
        autoSelect: true,
      },
    ],
    modalBody: `NYPD currently has a $6 billion budget, which is more than what the city spends on health, homeless services, youth development, and workforce development combined. Email your councilmember to demand divesting from police funding.`,
    modalTitle: `Email your councilmember to defund New York police`,
    modalUrl: [
      `https://www.changethenypd.org/NYCBudgetJustice, https://defund12.org/nyc`,
    ],
  }
}

export default buildEmail
